// <auto-generated />
using System;
using HoaP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HoaP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HoaP.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "bi bi-wifi",
                            Name = "Wi-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "bi bi-snow",
                            Name = "Klimatizace"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "bi bi-tv",
                            Name = "TV"
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                            Description = "",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-9012-cdef-123456789012",
                            Description = "",
                            Name = "Receptionist",
                            NormalizedName = "RECEPTIONIST"
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InsuranceCompanyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEmployed")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PersonalIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("bytea");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("InsuranceCompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HoaP.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "USD",
                            Name = "Americký dolar",
                            Rate = 22.50m,
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EUR",
                            Name = "Euro",
                            Rate = 24.80m,
                            Symbol = "€"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CZK",
                            Name = "Česká koruna",
                            Rate = 1.00m,
                            Symbol = "Kč"
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMainGuest")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hlavní 123",
                            City = "Praha",
                            Country = "Česká republika",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfExpiry = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfIssue = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentNumber = "UPfZOZeML/8zdKMpNPMYEDAjvBMvA4lJ1EkKaan+JbI=",
                            Email = "jan.novak@example.com",
                            FirstName = "Jan",
                            IsMainGuest = false,
                            LastName = "Novák",
                            Nationality = "Česká republika",
                            PersonalIdentificationNumber = "01ARHWk/UTDfIGKwiDQecBNoeBBlGggPB0AdBKO8tlE=",
                            Phone = "+420123456789",
                            PlaceOfBirth = "Praha",
                            PostalCode = "11000",
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Náměstí 456",
                            City = "Brno",
                            Country = "Česká republika",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfExpiry = new DateTime(2029, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfIssue = new DateTime(2019, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "Ei1UO1ebGxmlZG9GHoVeiDR/g1Z6VshaIB4iP71Bfgc=",
                            Email = "petr.svoboda@example.com",
                            FirstName = "Petr",
                            IsMainGuest = false,
                            LastName = "Svoboda",
                            Nationality = "Česká republika",
                            PersonalIdentificationNumber = "CYGgccJQfC+J4Gmd/J11rhYaIEdeB0RwzsFwnIliYLE=",
                            Phone = "+420987654321",
                            PlaceOfBirth = "Brno",
                            PostalCode = "60200",
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Sokolská 789",
                            City = "Ostrava",
                            Country = "Česká republika",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfExpiry = new DateTime(2031, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfIssue = new DateTime(2021, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "PZnyEoQtggje6sK98s7+sLwjIHWLljPLTmiIe7xdaRc=",
                            Email = "marie.cerna@example.com",
                            FirstName = "Marie",
                            IsMainGuest = false,
                            LastName = "Černá",
                            Nationality = "Česká republika",
                            PersonalIdentificationNumber = "zN9rm0vsSXiysy/EEDKUkrDBefnsT2BZ35ayu0Qn2s0=",
                            Phone = "+420654789123",
                            PlaceOfBirth = "Ostrava",
                            PostalCode = "70200",
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Jasná 321",
                            City = "Plzeň",
                            Country = "Česká republika",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1988, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfExpiry = new DateTime(2032, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfIssue = new DateTime(2022, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "C5IZRGb7/gezWOLhX2Y/s3OUW9dTYVOY5sL+s/W7sJg=",
                            Email = "anna.havlickova@example.com",
                            FirstName = "Anna",
                            IsMainGuest = false,
                            LastName = "Havlíčková",
                            Nationality = "Česká republika",
                            PersonalIdentificationNumber = "NpubJZRvrQ57G7DZOPnK5WAIn34gCkcGN50bSf/OGe4=",
                            Phone = "+420321654987",
                            PlaceOfBirth = "Plzeň",
                            PostalCode = "30100",
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Květná 159",
                            City = "Liberec",
                            Country = "Česká republika",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1995, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfExpiry = new DateTime(2031, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfIssue = new DateTime(2021, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "PE1akd89lOOmJhIDEjtHkvWFKPclOceUlgzNIELB7jk=",
                            Email = "tomas.prochazka@example.com",
                            FirstName = "Tomáš",
                            IsMainGuest = false,
                            LastName = "Procházka",
                            Nationality = "Česká republika",
                            PersonalIdentificationNumber = "QT/NDYSHPm+fSCzMYz4DB51q142hE2VVE0DPu4xL2U0=",
                            Phone = "+420159753468",
                            PlaceOfBirth = "Liberec",
                            PostalCode = "46000",
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Lípa 753",
                            City = "Ústí nad Labem",
                            Country = "Česká republika",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfExpiry = new DateTime(2030, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfIssue = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "UzCG5OR4NlpMA/oC2VVId6XdqdrbWjfGpbWIdETHaZM=",
                            Email = "petra.dvorakova@example.com",
                            FirstName = "Petra",
                            IsMainGuest = false,
                            LastName = "Dvořáková",
                            Nationality = "Česká republika",
                            PersonalIdentificationNumber = "AtQ7iBukXXFMZqFVn4iRgJ78P/T9yMX1bapfKQ1Lrm0=",
                            Phone = "+420753951852",
                            PlaceOfBirth = "Ústí nad Labem",
                            PostalCode = "40000",
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Březová 852",
                            City = "Hradec Králové",
                            Country = "Česká republika",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1987, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfExpiry = new DateTime(2031, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfIssue = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "VIB0eqGt29FcxkwHXLxbtDVuoIv29FTp4zeTLnTm6M4=",
                            Email = "jakub.novotny@example.com",
                            FirstName = "Jakub",
                            IsMainGuest = false,
                            LastName = "Novotný",
                            Nationality = "Česká republika",
                            PersonalIdentificationNumber = "TfjTHi4omI53hZmtvqSLyoJxLYh5AURRzp6Uik2Wdv4=",
                            Phone = "+420852456789",
                            PlaceOfBirth = "Hradec Králové",
                            PostalCode = "50000",
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Růžová 258",
                            City = "Zlín",
                            Country = "Česká republika",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfExpiry = new DateTime(2031, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfIssue = new DateTime(2021, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "Ti7kglpJD5jOzfBGE2DrDNRt0596g6NfqJVe187p0s0=",
                            Email = "lucie.krejcova@example.com",
                            FirstName = "Lucie",
                            IsMainGuest = false,
                            LastName = "Krejčová",
                            Nationality = "Česká republika",
                            PersonalIdentificationNumber = "RV2Wu18oJDhmVQCEEY3kGt1hL6EUoc6ldIdevMn7NFU=",
                            Phone = "+420258963147",
                            PlaceOfBirth = "Zlín",
                            PostalCode = "76000",
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Modrá 369",
                            City = "Karlovy Vary",
                            Country = "Česká republika",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1980, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfExpiry = new DateTime(2028, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfIssue = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "9BPNdr9Tz2gjeqYD/f14AibuBpZClYaN/SYEhG7CiKg=",
                            Email = "martin.fiala@example.com",
                            FirstName = "Martin",
                            IsMainGuest = false,
                            LastName = "Fiala",
                            Nationality = "Česká republika",
                            PersonalIdentificationNumber = "/z2nopl/Uetr/IjO0HcR3XINhOueL1PqnEdIDY/rVdM=",
                            Phone = "+420369258147",
                            PlaceOfBirth = "Karlovy Vary",
                            PostalCode = "36000",
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Violetová 741",
                            City = "Jihlava",
                            Country = "Česká republika",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfExpiry = new DateTime(2031, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfIssue = new DateTime(2021, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "OJ11aH5mQ3MnQlZe7j6+0lQ2/ZX4nKJhrfEKpQJEofY=",
                            Email = "barbora.kovarova@example.com",
                            FirstName = "Barbora",
                            IsMainGuest = false,
                            LastName = "Kovářová",
                            Nationality = "Česká republika",
                            PersonalIdentificationNumber = "aMnftLKDt+jCjg1Oxgfs/CQsjCRO+CZnT6XJBWQheJg=",
                            Phone = "+420741852963",
                            PlaceOfBirth = "Jihlava",
                            PostalCode = "58601",
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.HotelProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DIC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ICO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HotelProfiles");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.InsuranceCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InsuranceCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            Email = "",
                            Name = "Česká pojišťovna",
                            PhoneNumber = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "",
                            Email = "",
                            Name = "Kooperativa",
                            PhoneNumber = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 3,
                            Address = "",
                            Email = "",
                            Name = "Allianz",
                            PhoneNumber = "",
                            Website = ""
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfTaxableSupply")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prepayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VariableSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("IsPaid", "DueDate")
                        .HasDatabaseName("IX_Invoice_IsPaid_DueDate");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MealPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bez stravy",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Snídaně",
                            Price = 200m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Polopenze",
                            Price = 500m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Plná penze",
                            Price = 1000m
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<string>("GatewaySessionId")
                        .HasColumnType("text");

                    b.Property<string>("GatewayStatus")
                        .HasColumnType("text");

                    b.Property<string>("GatewayTransactionId")
                        .HasColumnType("text");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            IsActive = true,
                            Name = "Hotově"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            IsActive = true,
                            Name = "Kartou"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            IsActive = true,
                            Name = "Převodem"
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.RatePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxNights")
                        .HasColumnType("integer");

                    b.Property<int?>("MinNights")
                        .HasColumnType("integer");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceModifier")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("StartDate", "EndDate", "IsActive")
                        .HasDatabaseName("IX_RatePlan_DateRange_Active");

                    b.ToTable("RatePlans");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Adults")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Children")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReservationSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("ReservationStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialRequest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Reservation_CustomerId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("ReservationSourceId");

                    b.HasIndex("ReservationStatusId")
                        .HasDatabaseName("IX_Reservation_StatusId");

                    b.HasIndex("RoomId", "CheckIn", "CheckOut")
                        .HasDatabaseName("IX_Reservation_Room_Dates");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminNote = "Poznámka pro recepci",
                            Adults = 1,
                            CheckIn = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyId = 3,
                            CustomerId = 1,
                            IsCanceled = false,
                            MealPlanId = 2,
                            ReservationStatusId = 1,
                            RoomId = 1,
                            SpecialRequest = "Přistýlka",
                            TotalPrice = 6600m,
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AdminNote = "Poznámka pro recepci",
                            Adults = 2,
                            CheckIn = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyId = 3,
                            CustomerId = 2,
                            IsCanceled = false,
                            MealPlanId = 3,
                            ReservationStatusId = 1,
                            RoomId = 2,
                            SpecialRequest = "Dětská postýlka",
                            TotalPrice = 13500m,
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AdminNote = "Poznámka pro recepci",
                            Adults = 3,
                            CheckIn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyId = 3,
                            CustomerId = 3,
                            IsCanceled = false,
                            MealPlanId = 4,
                            ReservationStatusId = 1,
                            RoomId = 3,
                            SpecialRequest = "Bezlepková dieta",
                            TotalPrice = 19000m,
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.ReservationCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMainGuest")
                        .HasColumnType("boolean");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationCustomers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(105),
                            CustomerId = 6,
                            IsMainGuest = false,
                            ReservationId = 1,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(108)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(321),
                            CustomerId = 1,
                            IsMainGuest = true,
                            ReservationId = 1,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(323)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(325),
                            CustomerId = 2,
                            IsMainGuest = true,
                            ReservationId = 2,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(326)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(327),
                            CustomerId = 7,
                            IsMainGuest = false,
                            ReservationId = 2,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(327)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(329),
                            CustomerId = 3,
                            IsMainGuest = true,
                            ReservationId = 3,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(329)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(330),
                            CustomerId = 8,
                            IsMainGuest = false,
                            ReservationId = 3,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 504, DateTimeKind.Local).AddTicks(331)
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.ReservationSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReservationSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Walk-in"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Telefon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Web"
                        },
                        new
                        {
                            Id = 4,
                            Name = "OTA (Booking.com apod.)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Email"
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.ReservationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReservationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Potvrzená"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zrušená"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Čeká na potvrzení"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ubytován"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Odhlášen"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Nedostavil se"
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Skvělý pobyt, čistota na jedničku!",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            Rating = 5,
                            RoomId = 1,
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Příjemný personál a dobré jídlo.",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            Rating = 4,
                            RoomId = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Hezký pokoj, ale trochu hlučný soused.",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            Rating = 3,
                            RoomId = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsDisable")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAdults")
                        .HasColumnType("integer");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("RoomStatusId")
                        .HasDatabaseName("IX_Room_StatusId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 501, DateTimeKind.Local).AddTicks(7756),
                            CurrencyId = 3,
                            Description = "Jednolůžkový pokoj s výhledem na zahradu",
                            IsDisable = false,
                            MaxAdults = 1,
                            MaxChildren = 0,
                            Price = 2200m,
                            RoomNumber = "101",
                            RoomStatusId = 1,
                            RoomTypeId = 1,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(3445)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(4455),
                            CurrencyId = 3,
                            Description = "Dvoulůžkový pokoj",
                            IsDisable = false,
                            MaxAdults = 2,
                            MaxChildren = 1,
                            Price = 2700m,
                            RoomNumber = "102",
                            RoomStatusId = 1,
                            RoomTypeId = 2,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(4461)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(4465),
                            CurrencyId = 3,
                            Description = "Třílůžkový pokoj s výhledem na moře",
                            IsDisable = false,
                            MaxAdults = 3,
                            MaxChildren = 2,
                            Price = 3800m,
                            RoomNumber = "103",
                            RoomStatusId = 1,
                            RoomTypeId = 3,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(4466)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(4468),
                            CurrencyId = 3,
                            Description = "Rodinný pokoj",
                            IsDisable = false,
                            MaxAdults = 4,
                            MaxChildren = 3,
                            Price = 4500m,
                            RoomNumber = "104",
                            RoomStatusId = 1,
                            RoomTypeId = 4,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(4469)
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.RoomAmenity", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer");

                    b.HasKey("RoomId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("RoomAmenities");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.RoomStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoomStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Volný"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Obsazený"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mimo provoz"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Čeká na úklid"
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jednolůžkový pokoj"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dvoulůžkový pokoj"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Třílůžkový pokoj"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rodinný pokoj"
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsOneTime")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPerNight")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPerPerson")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            IsOneTime = false,
                            IsPerNight = false,
                            IsPerPerson = false,
                            Name = "Wellness vstup",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            IsOneTime = false,
                            IsPerNight = true,
                            IsPerPerson = false,
                            Name = "Parkování",
                            Price = 250m
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            IsOneTime = false,
                            IsPerNight = true,
                            IsPerPerson = false,
                            Name = "Domácí mazlíček",
                            Price = 300m
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            IsOneTime = false,
                            IsPerNight = false,
                            IsPerPerson = false,
                            Name = "Služba žehlení",
                            Price = 150m
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.ServiceReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("OriginalUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ReservationServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(9437),
                            Note = "Wellness pro 1 osobu",
                            OriginalUnitPrice = 0m,
                            Quantity = 1,
                            ReservationId = 1,
                            ServiceId = 1,
                            UnitPrice = 500m,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(9441)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(9829),
                            Note = "Parkování po celou dobu",
                            OriginalUnitPrice = 0m,
                            Quantity = 6,
                            ReservationId = 2,
                            ServiceId = 2,
                            UnitPrice = 250m,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(9832)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(9835),
                            Note = "Pes na pokoji",
                            OriginalUnitPrice = 0m,
                            Quantity = 11,
                            ReservationId = 3,
                            ServiceId = 3,
                            UnitPrice = 300m,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 55, 14, 503, DateTimeKind.Local).AddTicks(9836)
                        });
                });

            modelBuilder.Entity("HoaP.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HoaP.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HoaP.Domain.Entities.InsuranceCompany", "InsuranceCompany")
                        .WithMany()
                        .HasForeignKey("InsuranceCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("InsuranceCompany");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.InvoiceItem", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Payment", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Invoice");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.RatePlan", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("HoaP.Domain.Entities.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId");

                    b.Navigation("Room");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("HoaP.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Reservations")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HoaP.Domain.Entities.MealPlan", "MealPlan")
                        .WithMany()
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.ReservationSource", "ReservationSource")
                        .WithMany()
                        .HasForeignKey("ReservationSourceId");

                    b.HasOne("HoaP.Domain.Entities.ReservationStatus", "ReservationStatus")
                        .WithMany()
                        .HasForeignKey("ReservationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");

                    b.Navigation("MealPlan");

                    b.Navigation("ReservationSource");

                    b.Navigation("ReservationStatus");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.ReservationCustomer", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.Customer", "Customer")
                        .WithMany("ReservationCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.Reservation", "Reservation")
                        .WithMany("ReservationCustomers")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Review", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.Room", "Room")
                        .WithMany("Reviews")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Room", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HoaP.Domain.Entities.RoomStatus", "RoomStatus")
                        .WithMany()
                        .HasForeignKey("RoomStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("RoomStatus");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.RoomAmenity", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.Room", "Room")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.ServiceReservation", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.Reservation", "Reservation")
                        .WithMany("ServiceReservations")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.AppUser", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoaP.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HoaP.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Customer", b =>
                {
                    b.Navigation("ReservationCustomers");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("ReservationCustomers");

                    b.Navigation("ServiceReservations");
                });

            modelBuilder.Entity("HoaP.Domain.Entities.Room", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("RoomAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
