services:
  mysql:
    image: mysql:8
    container_name: hoap-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hoapdb
      MYSQL_USER: hoapuser
      MYSQL_PASSWORD: hoappass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: HoaP.Web/Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;user=hoapuser;password=hoappass;database=hoapdb

volumes:
  mysql_data:
